import dynamic from "next/dynamic";
import {districts} from "@/lib/mock-data";
const SabahMap=dynamic(()=>import("@/components/SabahMap"),{ssr:false,loading:()=> <div className="mapLoading">Loading geographic map…</div>});
const nav=["Dashboard","Live Weather","Disaster Map","Alerts","Risk Analysis","District Monitoring","Historical Analytics","Reports","Data Sources"];
export default function Home(){return <main className="shell">
 <aside className="sidebar"><div className="brand"><b>SD</b><div><strong>Sabah Disaster<br/>Intelligence Portal</strong><small>Operational starter</small></div></div><nav>{nav.map((n,i)=><button key={n} className={i===0?"active":""}>{["⌂","☁","◎","!","◈","▦","↗","▤","◉"][i]} <span>{n}</span>{n==="Alerts"&&<em>03</em>}</button>)}</nav><div className="system"><i/>Systems operational<small>Starter environment</small></div></aside>
 <section className="workspace"><header><div><h1>Sabah Situation Overview</h1><p>Real-time monitoring & risk intelligence</p></div><input aria-label="Search district" placeholder="Search district or locality…"/></header>
 <div className="content"><div className="advisory"><b>SIMULATED ADVISORY</b><span><strong>Persistent rainfall pattern detected in selected districts</strong><small>Refer to official authorities for confirmed warnings.</small></span></div>
 <div className="kpis">{[["Official alerts","—","Awaiting integration"],["Simulated notices","03","Prototype only"],["Elevated areas","04","Illustrative output"],["Districts monitored","27","Sabah coverage"],["Data coverage","68%","Medium confidence"],["Last update","19:10","MYT"]].map((k,i)=><article key={k[0]}><small>{k[0]}</small><strong className={i===2?"red":i===1?"orange":""}>{k[1]}</strong><span>{k[2]}</span></article>)}</div>
 <div className="primary"><section className="panel mapPanel"><div className="panelHead"><div><h2>Current Multi-Hazard Map</h2><p>OpenStreetMap base · simulated risk overlay</p></div><button>Risk</button></div><SabahMap/></section>
 <aside className="stack"><article className="panel intelligence"><label>AI DISASTER INTELLIGENCE</label><h2>Elevated flash-flood potential in selected areas</h2><p>Illustrative assessment combines simulated weather persistence and historical susceptibility.</p><ul><li>Flash flood <b>HIGH</b></li><li>Landslide <b>MODERATE</b></li><li>Strong wind <b>MODERATE</b></li></ul><small className="notice">AI-assisted assessment. Not an official warning.</small></article><article className="panel health"><h3>Data & system health</h3>{[["Application","ONLINE"],["MetMalaysia","NOT CONFIGURED"],["Risk engine","ONLINE"],["Qwen gateway","NOT CONFIGURED"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</article></aside></div>
 <section className="panel tablePanel"><div className="panelHead"><div><h2>District Risk Monitoring</h2><p>Simulation until validated sources are connected</p></div></div><div className="tableWrap"><table><thead><tr><th>District</th><th>Flood</th><th>Landslide</th><th>Storm</th><th>Overall</th><th>Confidence</th></tr></thead><tbody>{districts.map(d=><tr key={d.name}><td>{d.name}</td><td>{d.flood}</td><td>{d.landslide}</td><td>{d.storm}</td><td><b>{d.overall}</b></td><td>{d.confidence}%</td></tr>)}</tbody></table></div></section>
 </div></section><nav className="mobileNav">{["Home","Map","Alerts","Districts","More"].map(x=><button key={x}>{x}</button>)}</nav>
 </main>}
